### ISSUE TITLE
API V7

### ISSUE THREAD

**Issue by activenmb** [DoctorEenot/NumBuster-API#12]
Thank you for your app. Over time, some questions and problems have emerged.
1. apparently, numbuster updated the api and now uses the v7 api. Do you have any ideas for switching your app to the v7 api as well?
2. couldn't give your contact.

**Comment by DoctorEenot** [comment]
Thank you for the information on the api. Yeah, I know about these problems, but unfortunately I am currently don't have enough time to fix them :)

**Comment by activenmb** [comment]
Thanks for the answer. But still, could you at least give us your email address for a personal conversation?

**Comment by DoctorEenot** [comment]
Yeah, sure, dreenot@gmail.com

**Comment by DoctorEenot** [comment]
implementing new api version, is stated in TODO list.
