### ISSUE TITLE
v6_old_phone doesn't work

### ISSUE THREAD

**Issue by Bunder99** [DoctorEenot/NumBuster-API#13]
Hello! Thanks for your project!
I noticed that function **v6_old_phone** didn't work properly. It gives for the same number various and randomly generated names... Last week all were good, but this week not. Function **v6_old_search** gives names in hash-view.
What do you know about it? Did Numbuster change his API or close the door to unlimit requests?

**Comment by DoctorEenot** [comment]
Numbuster returns random data after big amounts of requests, it's a server side "protection", and I don't know their limits.

**Comment by Alexndrussianna** [comment]
Issue Tracker
