### ISSUE TITLE
Good Job. Decode Contacts[]

### ISSUE THREAD

**Issue by frech87** [DoctorEenot/NumBuster-API#6]
Hi. Very good jobs. If I buy pro version, I can see more contact name. But in free version I can't see more info, but API result have contacts[]
`"contacts": [
		{
			"firstName": "d78cc706ae0b03bc283dc1c119be6ef1",
			"lastName": "225a387247aefb8b1b00d7d94355b935",
			"count": 1
		},
		{
			"firstName": "e45cb1b8d805c6db64575fece1b26e0e",
			"lastName": "3e02d397a9dcc118cb4ac471ff20468a",
			"count": 1
		}
	],` 
How can I decode this part? May be have any ideas

**Comment by DoctorEenot** [comment]
Hi, thank you for your message, sorry I couldn't respond earlier. I'l see, how that data can be decided, if it's even possible.

**Comment by xIneffable** [comment]
That's will be great!

**Comment by DoctorEenot** [comment]
So, I've checked names, I think they are encoded in md5, if that's really the case, it would be impossible to decode them.

**Comment by frech87** [comment]
Hi. I buy premium, and after this data start come decode from server. But now my parser blocked, because, I am starting bruteforce number)))

**Comment by dva-re** [comment]
They really come decoded from the server when activating a spy-subscription. And the subscription is not expensive at all.

**Comment by DoctorEenot** [comment]
Ok, thx for information.
