### ISSUE TITLE
How to get information not as json format

### ISSUE THREAD

**Issue by xIneffable** [DoctorEenot/NumBuster-API#8]
Your programme is excellent but i need to get information simply in text, not in json format. How i can do it?

**Comment by DoctorEenot** [comment]
Hi, every function in file NumbusterApi.py returns json-encoded data by default, if you want to get just text, there are two ways to do it:
1) you can change 'return data.json()' to 'return data.text' (in Api functions)
2) change 'return data.json()' to 'return data'(in Api functions), you will get just response object from function, after you can get .text from that response

**Comment by xIneffable** [comment]
Thank you for your fast answer. But i get this error
Traceback (most recent call last):
  File "NumbusterAPI.py", line 326, in <module>
    print(api.v6_old_phone(numberinput))
  File "NumbusterAPI.py", line 45, in v6_old_phone
    return data.text()
TypeError: 'str' object is not callable

**Comment by DoctorEenot** [comment]
You don't need parentheses, just delete '()' and leave it like that: 'data.text'

**Comment by xIneffable** [comment]
I tried without parenthleses but i got problem with displaying words: 

{"id":2740865860,"firstName":"\u0421\u043e\u043d\u044c\u0447\u0438\u043a","lastName":"","profile":{"id":null,"firstName":"","lastName":"","phones":["380664243086"],"avatar":null,"branding":null,"counters":{"bans":0,"comments":0,"emotags":0}},"avatar":null,"branding":null,"bans":0,"rating":{"likes":0,"dislikes":0},"commentsCount":0,"region":"\u0423\u043a\u0440\u0430\u0438\u043d\u0430","carrier":"","tags":[],"contacts":[{"firstName":"3e1626af226576197cdbcfb4f470dc90","lastName":"225a387247aefb8b1b00d7d94355b935","count":1}],"phoneType":"PERSON","phones":["380664243086"],"questions":[],"left_requests":30,"suggestedProfile":{"firstName":null,"lastName":null},"contactsCount":1,"index":5,"antispy_subscription":false,"spy_subscription":false,"myCommentId":null,"comments":[],"notice":{"id":null,"text":null}}

It looks like \u0421\u043e\u043d\u044c\u0447\u0438\u043a

**Comment by DoctorEenot** [comment]
Oh, yeah, sorry, I forgot that names are encoded in utf-8, try '.content.decode('utf-8')' instead of '.text'.

**Comment by xIneffable** [comment]
It doesn't working yet

**Comment by xIneffable** [comment]
the same error

**Comment by DoctorEenot** [comment]
That`s not really an error, because that - '\u0421' is actual character in unicode. So, how are you getting that data, printing to console, writing to file, debugging, etc... ?

**Comment by DoctorEenot** [comment]
Probably, your actual data looks like that - '\\u0421\\u043e\\u043d\\u044c\\u0447\\u0438\\u043a' , if that`s the case, you must change '\\' to '\'

**Comment by DoctorEenot** [comment]
It can be done this way: data.text.replace('\\\\',\'\')

**Comment by xIneffable** [comment]
Okey, thanks

**Comment by xIneffable** [comment]
**I found how to solve the problem**. It is connected with Russian words. 
You should write - _"ensure_ascii=False"_
But i don't understand where i should write it. I tried to add it:
_data.content.decode('utf-8', ensure_ascii=False)_                      
I added it in every Api's function to data but i got such problem:

> Traceback (most recent call last):
>   File "NumbusterAPI.py", line 327, in <module>
>     print(api.v6_old_phone(numberinput))
>   File "NumbusterAPI.py", line 45, in v6_old_phone
>     return data.content.decode('utf-8', ensure_ascii=False)
> TypeError: 'ensure_ascii' is an invalid keyword argument for decode()

Maybe you can help me, where i should put _- "ensure_ascii=False" to solve problem_

P.S. Article where i found solution 
[Click ](https://ru.stackoverflow.com/questions/584129/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B0%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-json-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0-python) https://ru.stackoverflow.com/questions/584129/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B0%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-json-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0-python

**Comment by DoctorEenot** [comment]
Hi, data.content - binary content
data.content.decode('utf-8') - unicode text
only json.load/json.loads accepts argument "ensure_ascii=False".

Ex: json.loads(data.content.decode('utf-8'),ensure_ascii=False) - will return json(dict) object
by default data.json() returns the same

**Comment by xIneffable** [comment]
**Thank you for your fast answer.** 
I changed it as you said -
[CLICK](https://imgur.com/a/xx3ukac)
But i got error:

> Traceback (most recent call last):
>   File "NumbusterAPI.py", line 327, in <module>
>     print(api.v6_old_phone(numberinput))
>   File "NumbusterAPI.py", line 45, in v6_old_phone
>     return json.loads(data.content.decode('utf-8'),ensure_ascii=False)
> NameError: name 'json' is not defined

Sorry to be so dumb, I really don't understand json.

**Comment by DoctorEenot** [comment]
"import json"

By the way, "data.text.replace('\\','\')" - that didn`t help you?

**Comment by xIneffable** [comment]
**I had SyntaxError**

> return data.text.replace('\\','\')
>                                      ^
> SyntaxError: EOL while scanning string literal

[Click](https://imgur.com/a/L0PRLqM)

**Comment by DoctorEenot** [comment]
sorry, "data.text.replace('\\\\','\\')" my mistake.

**Comment by xIneffable** [comment]
Oops, quote change my code. 
I wrote as you said
return data.text.replace('\\','\')
                                     ^
SyntaxError: EOL while scanning string literal

**Comment by xIneffable** [comment]
But on the imgur you can see how i wrote it
[Click](https://imgur.com/a/L0PRLqM) - Imgur

**Comment by DoctorEenot** [comment]
Because "\\" is a "special character", you must write "\\\\" to get "\\"

**Comment by xIneffable** [comment]
> return data.text.replace('\\\','\\')
>                                      ^
> SyntaxError: EOL while scanning string literal

**Comment by DoctorEenot** [comment]
So, I have just checked, "data.text" - returns just plain text (what you asked for), so how did you get that data?: "\u0421\u043e\u043d\u044c\u0447\u0438\u043a"

**Comment by xIneffable** [comment]
Yes, exactly you have just wrote

**Comment by DoctorEenot** [comment]
So how did you get that data? 
"\u0421\u043e\u043d\u044c\u0447\u0438\u043a"

**Comment by xIneffable** [comment]
**I put number and get this**
Number: 38095**855**

> {"id":1900641349,"firstName":"\u0412\u0430\u0441\u044f","lastName":"","profile":{"id":null,"firstName":"","lastName":"","phones":["380954785545"],"avatar":null,"branding":null,"counters":{"bans":0,"comments":0,"emotags":0}},"avatar":null,"branding":null,"bans":0,"rating":{"likes":0,"dislikes":0},"commentsCount":0,"region":"\u0423\u043a\u0440\u0430\u0438\u043d\u0430","carrier":"","tags":[],"contacts":[{"firstName":"b49cfb5a1bd3525771cb4a2bbd159bca","lastName":"225a387247aefb8b1b00d7d94355b935","count":1}],"phoneType":"PERSON","phones":["380954785545"],"questions":[],"left_requests":30,"suggestedProfile":{"firstName":null,"lastName":null},"contactsCount":1,"index":5,"antispy_subscription":false,"spy_subscription":false,"myCommentId":null,"comments":[],"notice":{"id":null,"text":null}}

**Code looks like:**
https://imgur.com/a/VugSIDw

**Comment by DoctorEenot** [comment]
yeah, but I mean, did you write that in console?

**Comment by xIneffable** [comment]
no, build in my sublime

**Comment by DoctorEenot** [comment]
Maybe, but just, maybe, sublime doesn`t recognise unicode symbols. Try, for example, write output to file(file must be opened in utf-8) and check.

**Comment by DoctorEenot** [comment]
Because I don`t have that problem, and I don`t use Sublime, so if problem with Sublime, I can`t help you.

**Comment by xIneffable** [comment]
I have tried to launch this code into console and i got the same code as in sublime. I tried it to launch in my terminal - the same. I tried to change character set to utf-8 and other more - it doesn't help. And i think this problem will touch everyone who live in Russia or Ukraine. I see only 1 solution, it is use this **_ensure_ascii=False_**

**Comment by xIneffable** [comment]
But how it embed in code

**Comment by DoctorEenot** [comment]
So, why exactly you need text? mb it will be easier to use json, "return data.json()" or you are getting the same result?
"ensure_ascii=False" it would not help, if you want just text.

**Comment by xIneffable** [comment]
Ye, with "return data.json" - it works excellent. But i try to parse the information to my txt.
For example i want to get 'firstName' but i don't know how to get it in console or just in my txt

**Comment by DoctorEenot** [comment]
So... you can read about dictionaries there: https://www.geeksforgeeks.org/python-dictionary/

**Comment by xIneffable** [comment]
I've read this documentation but i don't know the name of the dictionary in your code, i've tried

> print(api.v6_old_phone['firstname'])
But it doesn't work

**Comment by DoctorEenot** [comment]
api.v6_old_phone - is a function

print(api.v6_old_phone()['firstname'])

**Comment by xIneffable** [comment]
Ohh, thank you so much, i really thankfull for your responsive and helping.
